sonar.projectKey=AparnaMounikau763_new-student-dashboard2
sonar.organization=aparnamounikau763
sonar.projectName=new-student_dashboard

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.10

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc

sonar.sourceEncoding=UTF-8
